# Generated by Django 4.2.6 on 2023-10-23 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorUser',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('date_verified', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('user.baseuser',),
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_under_verification_process', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(default='profile_pic.png', upload_to='')),
                ('citizenship_back', models.ImageField(default='citizenship_back.jpeg', upload_to='')),
                ('citizenship_front', models.ImageField(default='citizenship_front.jpeg', upload_to='')),
                ('digital_signature', models.ImageField(upload_to='')),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejected_message', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vendor_profile', to='vendor.vendoruser')),
            ],
        ),
    ]
